version: "3.8"
services:

  database:
    image: postgres
    env_file:
      - .env
    volumes:
      - ./modules/db/seed.sql:/docker-entrypoint-initdb.d/seed.sql

  frontend:
    build:
      context: .
    image: frontend_image
    ports:
      - "4200:4200"
    env_file:
      - .env
    volumes:
      - .:/app

volumes:
  data:
