version: "3.9"
services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: toggles/backend
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: toggles/frontend
    ports:
      - "4200:4200"
    volumes:
      - /app/node_modules
      - ./frontend:/app
