version: "3.9"
services:

  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    image: toggles/backend
    ports:
      - "3000:3000"
    environment:
      EDGE_ID: "${EDGE_ID}"
      EDGE_CONFIG_TOKEN: "${EDGE_CONFIG_TOKEN}"
      EDGE_CONFIG: "https://edge-config.vercel.com/${EDGE_ID}?token=${EDGE_CONFIG_TOKEN}"
      VERCEL_TOKEN: "${VERCEL_TOKEN}"
    volumes:
      - /app/node_modules
      - ./apps/backend:/app

  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    image: toggles/frontend
    ports:
      - "4200:4200"
    volumes:
      - /app/node_modules
      - ./apps/frontend:/app
