version: "3.8"
services:

  backend:
    build:
      context: ./backend
    image: backend_image
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/app

  frontend:
    build:
      context: ./frontend
    image: frontend_image
    ports:
      - "4200:4200"
    env_file:
      - .env
    volumes:
      - .:/app

volumes:
  data:
